export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const GET_FORMATIONS_BEGIN = 'GET_FORMATIONS_BEGIN'
export const GET_FORMATIONS_SUCCESS = 'GET_FORMATIONS_SUCCESS'

export const GET_ATTESTATIONS_BEGIN = 'GET_ATTESTATION_BEGIN'
export const GET_ATTESTATIONS_SUCCESS = 'GET_ATTESTATION_SUCCESS'

export const EDIT_FORMATION_BEGIN = 'EDIT_FORMATION_BEGIN'
export const EDIT_FORMATION_SUCCESS = 'EDIT_FORMATION_SUCCESS'

export const DELETE_FORMATION_BEGIN = 'DELETE_FORMATION_BEGIN'
export const DELETE_FORMATION_SUCCESS = 'DELETE_FORMATION_SUCCESS'
